packages:
  - apps/*
  - packages/*
  - packages/admin-core/*
  - packages/admin-core/ui/*
  - packages/admin-core/effects/*

catalogMode: prefer

catalog:
  '@tailwindcss/vite': ^4.3.1
  '@typescript/native-preview': latest
  '@types/node': ^24
  typescript: ~6
  tailwindcss: ^4.3.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  unplugin-vue: ^7.2.0
  tailwind-merge: ^3.6.0
  clsx: ^2.1.1
  npm-run-all2: ^9.0.2
  '@vue/test-utils': ^2.4.11
  happy-dom: ^20.11.1

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

catalogs:
  vue3:
    '@nuxt/ui': ^4.8.2
    '@vitejs/plugin-vue': ^6.0.6
    '@vitejs/plugin-vue-jsx': ^5.1.5
    pinia: ^3.0.4
    vue: ^3.5.35
    vue-router: ^5.1.0
    vite-plugin-vue-devtools: ^8.1.1
    vite-plugin-vue-layouts-next: ^2.1.0
    vue-tsc: latest

minimumReleaseAge: 1440

allowBuilds:
  esbuild: false
  vue-demi: false
