/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardToolbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const UButton: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/Button.vue'))['default']
  const UDashboardGroup: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue'))['default']
  const UDashboardNavbar: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue'))['default']
  const UDashboardPanel: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue'))['default']
  const UDashboardSidebar: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue'))['default']
  const UDashboardToolbar: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue'))['default']
  const UIcon: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue'))['default']
  const UNavigationMenu: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.8.2_@internationalized+date@3.12.2_@internationalized+number@3.6.7_@tiptap+e_95c32a4361467c73c0782fbc8f73a8ef/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue'))['default']
}
