/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UBreadcrumb: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const UBreadcrumb: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue'))['default']
  const UDashboardGroup: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue'))['default']
  const UDashboardNavbar: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue'))['default']
  const UDashboardPanel: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue'))['default']
  const UDashboardSidebar: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue'))['default']
  const UIcon: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue'))['default']
  const UNavigationMenu: (typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_351818cd59f94b2c1033a7989b7c181b/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue'))['default']
}
