/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/access/menu-visible-403': RouteRecordInfo<
      '/access/menu-visible-403',
      '/access/menu-visible-403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/workbench'
    >,
    '/dashboard/workbench': RouteRecordInfo<
      '/dashboard/workbench',
      '/dashboard/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/vite-plus': RouteRecordInfo<
      '/docs/vite-plus',
      '/docs/vite-plus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/internal/audit': RouteRecordInfo<
      '/internal/audit',
      '/internal/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/layout-example': RouteRecordInfo<
      '/layout-example',
      '/layout-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/map': RouteRecordInfo<
      '/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor': RouteRecordInfo<
      '/monitor',
      '/monitor',
      Record<never, never>,
      Record<never, never>,
      | '/monitor/jobs'
    >,
    '/monitor/jobs': RouteRecordInfo<
      '/monitor/jobs',
      '/monitor/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | '/reports/sales'
    >,
    '/reports/sales': RouteRecordInfo<
      '/reports/sales',
      '/reports/sales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system': RouteRecordInfo<
      '/system',
      '/system',
      Record<never, never>,
      Record<never, never>,
      | '/system/menu'
      | '/system/role'
      | '/system/settings'
      | '/system/settings/level-three'
      | '/system/settings/notification'
      | '/system/settings/theme'
      | '/system/user'
    >,
    '/system/menu': RouteRecordInfo<
      '/system/menu',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role': RouteRecordInfo<
      '/system/role',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings': RouteRecordInfo<
      '/system/settings',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | '/system/settings/level-three'
      | '/system/settings/notification'
      | '/system/settings/theme'
    >,
    '/system/settings/level-three': RouteRecordInfo<
      '/system/settings/level-three',
      '/system/settings/level-three',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/notification': RouteRecordInfo<
      '/system/settings/notification',
      '/system/settings/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/theme': RouteRecordInfo<
      '/system/settings/theme',
      '/system/settings/theme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user': RouteRecordInfo<
      '/system/user',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/403.vue': {
      routes:
        | '/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/404.vue': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/access/menu-visible-403.vue': {
      routes:
        | '/access/menu-visible-403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
        | '/dashboard/workbench'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/workbench.vue': {
      routes:
        | '/dashboard/workbench'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/docs/vite-plus.vue': {
      routes:
        | '/docs/vite-plus'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/internal/audit.vue': {
      routes:
        | '/internal/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/layout-example.vue': {
      routes:
        | '/layout-example'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/map.vue': {
      routes:
        | '/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitor.vue': {
      routes:
        | '/monitor'
        | '/monitor/jobs'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/monitor/jobs.vue': {
      routes:
        | '/monitor/jobs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reports.vue': {
      routes:
        | '/reports'
        | '/reports/sales'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/reports/sales.vue': {
      routes:
        | '/reports/sales'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system.vue': {
      routes:
        | '/system'
        | '/system/menu'
        | '/system/role'
        | '/system/settings'
        | '/system/settings/level-three'
        | '/system/settings/notification'
        | '/system/settings/theme'
        | '/system/user'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/system/menu.vue': {
      routes:
        | '/system/menu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/role.vue': {
      routes:
        | '/system/role'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings.vue': {
      routes:
        | '/system/settings'
        | '/system/settings/level-three'
        | '/system/settings/notification'
        | '/system/settings/theme'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/system/settings/level-three.vue': {
      routes:
        | '/system/settings/level-three'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings/notification.vue': {
      routes:
        | '/system/settings/notification'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/settings/theme.vue': {
      routes:
        | '/system/settings/theme'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/user.vue': {
      routes:
        | '/system/user'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
