export { default as AdminLayout } from './AdminLayout.vue'
export { IFrameRouterView } from './iframe'
export { useAdminTabbar } from './basic/tabbar'
export { buildAdminBreadcrumbPrefix, buildAdminBreadcrumbs } from './navigation/route-breadcrumb'
export type { AdminCurrentRouteRecord } from './navigation/route-breadcrumb'
export { closeAdminTab, createAdminTab, markActiveAdminTabs, upsertAdminTab } from './navigation/route-tab'
export { buildAdminMenuGroups, buildAdminMenus, markActiveAdminMenuGroups, markActiveAdminMenus } from './navigation/route-menu'
export type { AdminNavigationRouteRecord as AdminBreadcrumbRouteRecord, AdminNavigationRouteRecord as AdminRouteRecord } from '@monorepo-admin-core/types'
export type { BuildAdminMenuGroupsOptions, BuildAdminMenusOptions } from './navigation/route-menu'
